/obj/structure/spawner/ice_moon/demonic_portal
	name = "demonic portal"
	desc = "A portal that goes to another world, normal creatures couldn't survive there. When it collapses, who knows where it will go?"
	icon_state = "redspace"
	icon = 'modular_dripstation/icons/mob/nether.dmi'
	mob_types = list(/mob/living/simple_animal/hostile/asteroid/ice_demon)
	light_range = 2
	light_power = 2
	light_color = COLOR_SOFT_RED
	spawn_time = 500
	resistance_flags = null

/obj/structure/spawner/ice_moon/demonic_portal/clear_rock()
	for(var/turf/F in RANGE_TURFS(3, src))
		if(abs(src.x - F.x) + abs(src.y - F.y) > 5)
			continue
		if(ismineralturf(F))
			var/turf/closed/mineral/M = F
			M.ScrapeAway(null, CHANGETURF_IGNORE_AIR)

/obj/structure/spawner/ice_moon/demonic_portal/Initialize()
	. = ..()
	AddComponent(/datum/component/gps, "Netheric Signal")

/obj/structure/spawner/ice_moon/demonic_portal/deconstruct(disassembled)
	new /obj/effect/collapsing_demonic_portal(loc)
	return ..()

/obj/structure/spawner/ice_moon/demonic_portal/ice_whelp
	mob_types = list(/mob/living/simple_animal/hostile/asteroid/ice_whelp)

/obj/structure/spawner/ice_moon/demonic_portal/snowlegion
	mob_types = list(/mob/living/simple_animal/hostile/asteroid/hivelord/legion/snow/tendril)

/obj/effect/collapsing_demonic_portal
	name = "collapsing demonic portal"
	desc = "It's slowly fading! Get ready to fight whatever comes through!"
	layer = TABLE_LAYER
	light_range = 3
	light_power = 3
	light_color = COLOR_SOFT_RED
	light_system = STATIC_LIGHT
	icon = 'modular_dripstation/icons/mob/nether.dmi'
	icon_state = "nether"
	anchored = TRUE
	density = TRUE

/obj/effect/collapsing_demonic_portal/Initialize()
	. = ..()
	playsound(loc,'sound/effects/tendril_destroyed.ogg', 200, FALSE, 50, TRUE, TRUE)
	visible_message("<span class='boldannounce'>[src] begins to collapse! As it fails, it connects to a random dimensional point and pulls through what it finds!</span>")
	animate(src, transform = matrix().Scale(0, 1), alpha = 50, time = 5 SECONDS)
	addtimer(CALLBACK(src, .proc/collapse), 5 SECONDS)

/**
 * Handles portal deletion
 *
 */
/obj/effect/collapsing_demonic_portal/proc/collapse()
	drop_loot()
	qdel(src)

/**
 * Drops loot from the portal. Uses variable difficulty based on drops- more valulable rewards will also add additional enemies to the attack wave.
 * If you manage to win big and get a bunch of major rich loot, you will also be faced with a big mob of angries.
 * Absolutely deranged use of probability code below, trigger warning
 */
/obj/effect/collapsing_demonic_portal/proc/drop_loot()
	visible_message("<span class='warning'>Something slips out of [src]!</span>")
	var/loot = rand(1, 23)
	switch(loot)
		if(1)//Clown hell. God help you if you roll this.
			visible_message("<span class='userdanger'>You can hear screaming and joyful honking.</span>")//now THIS is what we call a critical failure
			playsound(loc,'sound/spookoween/ghosty_wind.ogg', 100, FALSE, 50, TRUE, TRUE)
			playsound(loc,'sound/spookoween/scary_horn3.ogg', 100, FALSE, 50, TRUE, TRUE)
			if(prob(15))
				new /mob/living/simple_animal/hostile/retaliate/clown/clownhulk(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/longface(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/clownhulk/chlown(loc)
				new /obj/item/shield/energy/bananium(loc)
			if(prob(35))
				new /mob/living/simple_animal/hostile/retaliate/clown/banana(loc)
			if(prob(35))
				new /mob/living/simple_animal/hostile/retaliate/clown/fleshclown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/clownhulk/chlown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/honkling(loc)
			if(prob(25))
				new /obj/item/grenade/spawnergrenade/clown(loc)
				new /obj/item/grenade/spawnergrenade/clown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/clownhulk(loc)
			if(prob(10))
				new /mob/living/simple_animal/hostile/retaliate/clown/mutant/blob(loc)//oh god oh fuck
				new /obj/machinery/syndicatebomb/badmin/clown(loc)
			if(prob(25))
				new /obj/item/veilrender/honkrender/honkhulkrender(loc)
			else
				new /obj/item/veilrender/honkrender(loc)
			if(prob(35))
				new /obj/item/storage/backpack/duffelbag/clown/syndie(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/fleshclown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/honkling(loc)
			else
				new /obj/item/storage/backpack/duffelbag/clown/cream_pie(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/honkling(loc)
			if(prob(25))
				new /obj/item/borg/upgrade/transform/clown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/honkling(loc)
			if(prob(35))
				new /obj/item/megaphone/clown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/honkling(loc)
			if(prob(25))
				new /obj/item/reagent_containers/spray/waterflower/lube(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/fleshclown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/fleshclown(loc)
			if(prob(35))
				new /obj/item/clothing/suit/space/hardsuit/clown(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/fleshclown(loc)
			if(prob(35))
				new /obj/item/gun/magic/staff/honk(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/fleshclown(loc)
			if(prob(25))
				new /obj/item/clothing/shoes/clown_shoes/banana_shoes/combat(loc)
				new /mob/living/simple_animal/hostile/retaliate/clown/fleshclown(loc)
			if(prob(25))//you lost
				new /obj/item/circlegame(loc)
			new /obj/item/stack/sheet/mineral/bananium(loc)
			new /turf/open/floor/mineral/bananium(loc)
		if(2)//basic demonic incursion
			visible_message("<span class='userdanger'>You glimpse an indescribable abyss in the portal. Horrifying monsters appear in a gout of flame.</span>")
			playsound(loc,'sound/hallucinations/wail.ogg', 200, FALSE, 50, TRUE, TRUE)
			if(prob(35))
				new /obj/item/clothing/glasses/godeye(loc)
				new /mob/living/simple_animal/hostile/netherworld/migo(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
			if(prob(45))
				new /obj/item/wisp_lantern(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
				new /mob/living/simple_animal/hostile/netherworld(loc)
			if(prob(25))
				new /obj/item/organ/heart/demon(loc)
				new /mob/living/simple_animal/hostile/netherworld(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
			if(prob(5))
				new /obj/item/his_grace(loc)//trust me, it's not worth the trouble.
				new /mob/living/simple_animal/hostile/netherworld/migo(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
				new /mob/living/simple_animal/hostile/netherworld/migo(loc)
			if(prob(45))
				new /obj/item/nullrod/staff(loc)
				new /mob/living/simple_animal/hostile/netherworld/migo(loc)
			if(prob(30))
				new /obj/item/immortality_talisman(loc)
				new /mob/living/simple_animal/hostile/netherworld/migo(loc)
			if(prob(30))
				new /obj/item/shared_storage/red(loc)
				new /mob/living/simple_animal/hostile/netherworld(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
			if(prob(30))
				new /obj/item/kitchen/knife/envy(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
			if(prob(30))
				new /obj/item/book/granter/action/spell/traps(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
				new /mob/living/simple_animal/hostile/netherworld/migo(loc)
			if(prob(30))
				new /obj/item/kitchen/knife/envy(loc)
				new /mob/living/simple_animal/hostile/netherworld/blankbody(loc)
				new /mob/living/simple_animal/hostile/netherworld(loc)
			new /mob/living/simple_animal/hostile/netherworld/migo(loc)
			new /mob/living/simple_animal/hostile/netherworld(loc)
			new /turf/open/indestructible/necropolis(loc)
		if(3)//skeleton/religion association, now accepting YOUR BONES
			visible_message("<span class='userdanger'>Bones rattle and strained voices chant a forgotten god's name.</span>")
			playsound(loc,'sound/ambience/ambiholy.ogg', 100, FALSE, 50, TRUE, TRUE)
			if(prob(30))
				new /obj/item/reagent_containers/glass/bottle/potion/flight(loc)
				new /mob/living/simple_animal/hostile/skeleton/templar(loc)
			else
				new /obj/item/clothing/neck/necklace/memento_mori(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
				new /mob/living/simple_animal/hostile/skeleton/templar(loc)
			if(prob(35))
				new /obj/item/storage/box/holy_grenades(loc)
				new /mob/living/simple_animal/hostile/skeleton/templar(loc)
				new /mob/living/simple_animal/hostile/skeleton/templar(loc)
			if(prob(40))
				new /obj/item/claymore(loc)
				new /mob/living/simple_animal/hostile/skeleton/templar(loc)
			if(prob(45))
				new /obj/item/gun/ballistic/bow(loc)
				new /obj/item/storage/belt/quiver(loc)
				new /obj/item/ammo_casing/reusable/arrow/bronze(loc)
				new /obj/item/ammo_casing/reusable/arrow/bronze(loc)
				new /obj/item/ammo_casing/reusable/arrow/bronze(loc)
				new /obj/item/ammo_casing/reusable/arrow/bronze(loc)
				new /obj/item/ammo_casing/reusable/arrow/bronze(loc)
				new /mob/living/simple_animal/hostile/skeleton/templar(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
			if(prob(30))
				new /obj/item/stack/sheet/mineral/wood/fifty(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
			if(prob(35))
				new /obj/item/melee/bostaff(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
			if(prob(25))
				new /obj/item/shield/riot/roman(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
			if(prob(55))
				new /obj/item/clothing/suit/armor/riot/knight/blue(loc)
				new /obj/item/clothing/head/helmet/knight/blue(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
			if(prob(35))
				new /obj/item/disk/design_disk/adv/knight_gear(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
				new /mob/living/simple_animal/hostile/skeleton(loc)
			new /obj/item/instrument/trombone(loc)
			new /obj/item/stack/sheet/bone(loc)
			new /obj/item/stack/sheet/bone(loc)
			new /obj/item/stack/sheet/bone(loc)
			new /obj/item/stack/sheet/bone(loc)
			new /mob/living/simple_animal/hostile/skeleton/templar(loc)
			new /turf/open/floor/mineral/silver(loc)
		if(4)//hogwart's school of witchcraft and wizardry. Featuring incredible loot at incredibly low chances
			visible_message("<span class='userdanger'>You hear the sounds of a terrible magical duel!</span>")
			playsound(loc,'sound/spookoween/ghost_whisper.ogg', 100, FALSE, 50, TRUE, TRUE)
			if(prob(35))
				new /obj/item/organ/heart/cursed/wizard(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			if(prob(45))
				new /obj/item/book/granter/action/spell/summonitem(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/academywizard/soldier(loc)
			if(prob(35))
				new /obj/item/book/granter/action/spell/random(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			if(prob(25))
				new /obj/item/book/granter/action/spell/sacredflame(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/academywizard/soldier(loc)
			if(prob(35))
				new /obj/item/book/granter/action/spell/shapechange(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/academywizard/soldier(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			if(prob(25))
				new /obj/item/gun/magic/staff/chaos(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			if(prob(25))
				new /obj/item/book/granter/action/spell/charge(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			if(prob(25))
				new /obj/item/book/granter/action/spell/fireball(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			if(prob(25))
				new /obj/item/gun/magic/wand/polymorph(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			if(prob(35))
				new /obj/item/guardiancreator(loc)
				new /mob/living/simple_animal/hostile/academywizard(loc)
				new /mob/living/simple_animal/hostile/wizard(loc)
			new /obj/item/upgradescroll(loc)
			new /obj/item/gun/magic/wand/fireball/inert(loc)
			new /mob/living/simple_animal/hostile/wizard(loc)
			new /mob/living/simple_animal/hostile/academywizard(loc)
			new /turf/open/floor/wood/large(loc)
		if(5)//syndicate incursion. Again, high-quality loot at low chances, this time with excessive levels of danger
			visible_message("<span class='userdanger'>Radio chatter echoes out from the portal. Red-garbed figures step through, weapons raised.</span>")
			playsound(loc,'modular_dripstation/sound/effects/radiohiss.ogg', 300, FALSE, 50, TRUE, TRUE)
			playsound(loc,'sound/ambience/antag/tatoralert.ogg', 200, FALSE, 50, TRUE, TRUE)
			if(prob(65))
				if(prob(85))
					new /obj/item/clothing/suit/space/hardsuit/syndi(loc)
					new /mob/living/simple_animal/hostile/syndicate/ranged/smg/space(loc)
				else
					if(prob(50))
						new /obj/item/clothing/suit/space/hardsuit/syndi/engineering/syndicate/winter(loc)
						new /mob/living/simple_animal/hostile/syndicate/melee/sword/space/stormtrooper(loc)
					else
						new /obj/item/clothing/suit/space/hardsuit/syndi/bloodred/winter(loc)
						new /mob/living/simple_animal/hostile/syndicate/melee/space/stormtrooper(loc)
						new /mob/living/simple_animal/hostile/syndicate/ranged/shotgun/space/stormtrooper(loc)
			if(prob(25))//the real prize
				new /obj/effect/spawner/lootdrop/donkpockets(loc)
				new /obj/effect/spawner/lootdrop/donkpockets(loc)
				new /obj/effect/spawner/lootdrop/donkpockets(loc)
			if(prob(35))
				new /obj/item/clothing/shoes/magboots/syndie(loc)
				new /mob/living/simple_animal/hostile/syndicate/ranged/smg/space(loc)
			if(prob(25))
				new /obj/item/gun/ballistic/automatic/pistol/suppressed(loc)
				new /obj/item/ammo_box/magazine/m10mm(loc)
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/icemoon(loc)
			if(prob(25))
				new /obj/item/gun/ballistic/automatic/pistol/glock18(loc)
				new /obj/item/ammo_box/magazine/pistolm9mm(loc)
				new /obj/item/ammo_box/magazine/pistolm9mm(loc)
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/icemoon(loc)
			if(prob(35))
				new /obj/item/clothing/gloves/rapid(loc)
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/space(loc)
				new /mob/living/simple_animal/hostile/syndicate/ranged/smg/space(loc)
			if(prob(35))
				new /obj/item/wrench/combat(loc)
				new /obj/item/storage/toolbox/syndicate(loc)
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/space(loc)
			if(prob(35))
				new /obj/item/storage/fancy/cigarettes/cigpack_syndicate(loc)
			if(prob(35))
				new /obj/item/borg/upgrade/transform/assault(loc)
				new /mob/living/simple_animal/hostile/syndicate/ranged/smg/icemoon(loc)
			if(prob(25))
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/icemoon(loc)
				new /obj/item/storage/backpack/duffelbag/syndie/med(loc)
			if(prob(35))
				new /obj/item/storage/belt/military(loc)
				new /mob/living/simple_animal/hostile/syndicate/ranged/smg/icemoon(loc)
			if(prob(35))
				new /obj/item/syndie_crusher(loc)
				new /mob/living/simple_animal/hostile/syndicate/ranged/smg/icemoon(loc)
				new /mob/living/simple_animal/hostile/syndicate/ranged/smg/space(loc)
			if(prob(25))
				new /obj/item/card/id/syndicate/anyone(loc)
			if(prob(35))
				new /obj/item/clothing/glasses/thermal(loc)
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/icemoon(loc)
			if(prob(25))
				new /obj/item/shield/energy(loc)
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/space(loc)
			if(prob(35))
				new /obj/item/hypospray/qmc(loc)
				new /mob/living/simple_animal/hostile/syndicate/ranged/shotgun/icemoon(loc)
				new /mob/living/simple_animal/hostile/syndicate/melee/sword/icemoon(loc)
			//if(prob(25))
			//	new /obj/item/card/emag(loc)
			//	new /mob/living/simple_animal/hostile/syndicate/melee/sword/icemoon(loc)
			new /mob/living/simple_animal/hostile/syndicate/ranged/smg/space(loc)
			new /mob/living/simple_animal/hostile/syndicate/melee/sword/space(loc)
			new /turf/open/floor/mineral/plastitanium/red(loc)
		if(6)//;HELP BLOB IN MEDICAL
			visible_message("<span class='userdanger'>You hear a robotic voice saying something about a \"Delta-level biohazard\".</span>")
			playsound(loc,'sound/ai/default/outbreak5.ogg', 100, FALSE, 50, TRUE, TRUE)
			playsound(loc,'sound/misc/bloblarm.ogg', 50, FALSE, 50, TRUE, TRUE)
			if(prob(35))
				new /obj/item/circuitboard/machine/chem_dispenser(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(35))
				new /obj/item/storage/firstaid/hypospray/vial(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(15))
				new /obj/item/gun/medbeam(loc)
				new /mob/living/simple_animal/hostile/blob/blobbernaut/independent(loc)
			if(prob(45))
				new /obj/item/defibrillator(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(45))
				new /obj/item/circuitboard/machine/stasis(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(45))
				new /obj/item/stack/medical/suture/medicated(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(45))
				new /obj/item/stack/medical/mesh/advanced(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(35))
				new /obj/item/gun/syringe/syndicate(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(25))
				new /obj/item/healthanalyzer/advanced(loc)
			if(prob(35))
				new /obj/item/storage/firstaid/advanced(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(35))
				new /obj/item/storage/firstaid/tactical(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
				new /mob/living/simple_animal/hostile/blob/blobbernaut/independent(loc)
			else
				new /obj/item/storage/firstaid/regular(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			if(prob(45))
				new /obj/item/rod_of_asclepius(loc)
			if(prob(35))
				new /obj/effect/mob_spawn/human/corpse/terragov/infantry(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			else
				new /obj/effect/mob_spawn/human/doctor(loc)
			if(prob(35))
				new /obj/effect/mob_spawn/human/corpse/terragov/infantry(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			else
				new /obj/effect/mob_spawn/human/doctor(loc)
			if(prob(35))
				new /obj/effect/mob_spawn/human/corpse/terragov/infantry(loc)
				new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			else
				new /obj/effect/mob_spawn/human/doctor(loc)
			new /obj/item/healthanalyzer(loc)
			new /turf/open/floor/carpet/cyan(loc)
			new /mob/living/simple_animal/hostile/blob/blobbernaut/independent(loc)
			new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
			new /mob/living/simple_animal/hostile/blob/blobspore/weak(loc)
		if(7)//teleporty ice world. Incomplete.
			visible_message("<span class='userdanger'>You glimpse a frozen, empty plane. Something stirs in the fractal abyss.</span>")
			playsound(loc,'sound/ambience/ambisin3.ogg', 150, FALSE, 50, TRUE, TRUE)
			if(prob(45))
				new /obj/item/warp_cube/red(loc)
				new /obj/item/warp_cube(loc)
				new /mob/living/simple_animal/hostile/asteroid/ice_demon(loc)
			if(prob(45))
				new /obj/item/clothing/suit/drfreeze_coat(loc)
				new /obj/item/clothing/under/costume/drfreeze(loc)
				new /mob/living/simple_animal/hostile/asteroid/ice_demon(loc)
			if(prob(35))
				new /obj/item/gun/magic/wand/teleport(loc)
				new /mob/living/simple_animal/hostile/asteroid/ice_demon(loc)
				new /mob/living/simple_animal/hostile/bear/snow(loc)
			if(prob(45))
				new /obj/item/freeze_cube(loc)
				new /mob/living/simple_animal/hostile/asteroid/ice_demon(loc)
			if(prob(55))
				new /obj/item/clothing/shoes/winterboots/ice_boots(loc)
				new /mob/living/simple_animal/hostile/bear/snow(loc)
				new /obj/effect/decal/remains/human(loc)
			new /mob/living/simple_animal/hostile/asteroid/ice_demon(loc)
			new /turf/open/floor/plating/ice/smooth(loc)
		if(8)//FUCK FUCK HELP SWARMERS IN VAULT
			visible_message("<span class='userdanger'>Something beeps. Small, glowing forms spill out of the portal en masse!</span>")
			playsound(loc,'sound/ambience/ambitech.ogg', 150, FALSE, 50, TRUE, TRUE)
			new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(45))
				new /obj/item/construction/rcd/loaded(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(35))
				new /obj/item/holosign_creator/atmos(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/vendor(loc)
				new /obj/item/vending_refill/engivend(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(45))
				new /obj/item/tank/jetpack/oxygen(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(25))
				new /obj/item/stack/sheet/metal/fifty(loc)
				new /obj/item/grenade/chem_grenade/smart_metal_foam(loc)
				new /obj/item/grenade/chem_grenade/smart_metal_foam(loc)
				new /obj/item/grenade/chem_grenade/smart_metal_foam(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(35))
				new /obj/item/stack/sheet/metal/fifty(loc)
				new /obj/item/clothing/glasses/meson/engine(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(25))
				new /obj/item/stack/sheet/metal/twenty(loc)
				new /obj/
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(25))
				new /obj/item/storage/toolbox/infiltrator(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(25))
				new /obj/machinery/portable_atmospherics/canister/oxygen(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
			if(prob(35))
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
				new /obj/item/clothing/gloves/color/yellow(loc)
			if(prob(35))
				new /mob/living/simple_animal/hostile/swarmer/ai(loc)
				new /obj/item/clothing/gloves/color/yellow(loc)
			new /obj/effect/mob_spawn/human/engineer(loc)
			new /turf/open/floor/circuit/telecomms(loc)
		if(9)//Literally blood-drunk.
			visible_message("<span class='userdanger'>Blood sprays from the portal. An ichor-drenched figure steps through!</span>")
			playsound(loc,'sound/magic/enter_blood.ogg', 150, FALSE, 50, TRUE, TRUE)
			new /obj/effect/gibspawner/human(loc)
			new /obj/effect/gibspawner/human(loc)
			new /obj/effect/gibspawner/human(loc)
			new /mob/living/simple_animal/hostile/megafauna/blood_drunk_miner/doom(loc)
			if(prob(50))
				new /obj/item/gem/bloodstone(loc)
			if(prob(25))
				new /obj/item/seeds/tomato/blood(loc)
			new /turf/open/floor/plating/asteroid/basalt(loc)
		if(10)//Now's your chance to be a [[BIG SHOT]]
			visible_message("<span class='userdanger'>You hear the sound of big money and bigger avarice.</span>")
			playsound(loc,'sound/lavaland/cursed_slot_machine_jackpot.ogg', 150, FALSE, 50, TRUE, TRUE)
			new /obj/structure/cursed_slot_machine(loc)
			if(prob(35))
				new /obj/item/stack/spacecash/c1000(loc)
				new /obj/item/stack/spacecash/c1000(loc)
				new /obj/item/coin/gold(loc)
				new /mob/living/simple_animal/hostile/faithless(loc)
			if(prob(35))
				new /obj/item/gem/fdiamond(loc)
				new /mob/living/simple_animal/hostile/faithless(loc)
			else
				new /obj/item/gem/rupee(loc)
			if(prob(35))
				new /obj/item/coin/gold(loc)
				new /obj/item/coin/gold(loc)
				new /obj/item/stack/sheet/mineral/gold/twenty(loc)
				new /mob/living/simple_animal/hostile/faithless(loc)
			if(prob(35))
				new /obj/item/storage/fancy/cigarettes/cigpack_robustgold(loc)
				new /mob/living/simple_animal/hostile/faithless(loc)
			if(prob(35))
				new /obj/item/clothing/head/collectable/petehat(loc)
				new /mob/living/simple_animal/hostile/faithless(loc)
			new /mob/living/simple_animal/hostile/faithless(loc)
			new /mob/living/simple_animal/hostile/faithless(loc)
			new /turf/open/floor/mineral/gold(loc)
		if(11)//hivebot factory
			visible_message("<span class='userdanger'>You catch a brief glimpse of a vast production complex. One of the assembly lines outputs through the portal!</span>")
			playsound(loc,'sound/ambience/antag/clockcultalr.ogg', 100, FALSE, 50, TRUE, TRUE)
			if(prob(45))
				new /obj/item/stack/sheet/mineral/adamantine/twenty(loc)
				new /obj/item/stack/sheet/runed_metal/twenty(loc)
				new /obj/item/stack/sheet/mineral/mythril/twenty(loc)
				new /mob/living/simple_animal/hostile/hivebot(loc)
			if(prob(35))
				new /obj/item/stack/sheet/mineral/adamantine/twenty(loc)
				new /obj/item/stack/sheet/runed_metal/twenty(loc)
				new /obj/item/stack/sheet/mineral/mythril/twenty(loc)
				new /mob/living/simple_animal/hostile/hivebot(loc)
			if(prob(25))
				new /obj/item/stack/sheet/mineral/adamantine/twenty(loc)
				new /obj/item/stack/sheet/runed_metal/twenty(loc)
				new /obj/item/stack/sheet/mineral/mythril/twenty(loc)
				new /mob/living/simple_animal/hostile/hivebot/strong(loc)
			if(prob(35))
				new /obj/item/stack/sheet/mineral/silver/twenty(loc)
				new /obj/item/stack/sheet/mineral/titanium/twenty(loc)
				new /obj/item/stack/sheet/mineral/gold/twenty(loc)
				new /mob/living/simple_animal/hostile/hivebot/strong(loc)
			if(prob(35))
				new /obj/item/circuitboard/computer/solar_control(loc)
				new /obj/item/electronics/tracker(loc)
				new /obj/item/solar_assembly(loc)
				new /obj/item/solar_assembly(loc)
				new /obj/item/solar_assembly(loc)
				new /obj/item/solar_assembly(loc)
			if(prob(45))
				new /obj/item/stack/circuit_stack(loc)
				new /mob/living/simple_animal/hostile/hivebot/mechanic(loc)
			if(prob(45))
				new /obj/item/circuitboard/machine/dna_vault(loc)
				new /mob/living/simple_animal/hostile/hivebot/mechanic(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/recycler(loc)
				new /mob/living/simple_animal/hostile/hivebot/mechanic(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/recharger(loc)
				new /mob/living/simple_animal/hostile/hivebot/mechanic(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/smoke_machine(loc)
				new /mob/living/simple_animal/hostile/hivebot/mechanic(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/ore_silo(loc)
				new /mob/living/simple_animal/hostile/hivebot/mechanic(loc)
			if(prob(35))
				new /obj/item/stack/sheet/mineral/adamantine/ten(loc)
				new /obj/item/stack/sheet/runed_metal/ten(loc)
				new /obj/item/stack/sheet/mineral/mythril/ten(loc)
				new /mob/living/simple_animal/hostile/hivebot/strong(loc)
			//if(prob(35))
			//	new /obj/item/circuitboard/machine/medipen_refiller(loc)
			//	new /mob/living/simple_animal/hostile/hivebot(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/stasis(loc)
				new /mob/living/simple_animal/hostile/hivebot(loc)
			if(prob(50))
				new /obj/item/stack/sheet/metal/fifty(loc)
				new /obj/item/stack/sheet/glass/fifty(loc)
				new /obj/item/stack/cable_coil/yellow(loc)
				new /obj/item/storage/box/lights/bulbs(loc)
				new /mob/living/simple_animal/hostile/hivebot(loc)
			new /mob/living/simple_animal/hostile/hivebot(loc)
			new /mob/living/simple_animal/hostile/hivebot/strong(loc)
			new /obj/machinery/conveyor(loc)
			new /turf/open/floor/circuit/red(loc)
		if(12)//miner's last moments
			visible_message("<span class='userdanger'>The familiar sound of an ash storm greets you. A miner steps through the portal, stumbles, and collapses.</span>")
			playsound(loc,'sound/weather/ashstorm/outside/weak_end.ogg', 150, FALSE, 50, TRUE, TRUE)
			if(prob(35))
				new /obj/item/circuitboard/machine/mining_equipment_vendor(loc)
				new /mob/living/simple_animal/hostile/asteroid/goliath/beast(loc)
			if(prob(35))
				new /obj/item/reagent_containers/autoinjector/medipen/survival(loc)
			if(prob(35))
				new /obj/item/fulton_core(loc)
				new /obj/item/extraction_pack(loc)
				new /mob/living/simple_animal/hostile/asteroid/goliath/beast(loc)
			if(prob(45))
				new /obj/item/t_scanner/adv_mining_scanner/lesser(loc)
				new /mob/living/simple_animal/hostile/asteroid/goliath/beast(loc)
			if(prob(45))
				new /obj/item/melee/gibtonite(loc)
				new /mob/living/simple_animal/hostile/asteroid/goliath/beast(loc)
			if(prob(45))
				new /obj/item/clothing/glasses/meson/night(loc)
				new /mob/living/simple_animal/hostile/asteroid/goliath/beast(loc)
			if(prob(50))
				new /obj/item/kinetic_crusher(loc)
			else
				new /obj/item/gun/energy/kinetic_accelerator(loc)
			new /mob/living/simple_animal/hostile/asteroid/goliath/beast(loc)
			new /mob/living/simple_animal/hostile/asteroid/goliath/beast(loc)
			new /mob/living/simple_animal/hostile/asteroid/goliath/beast/ancient(loc)
			new /obj/effect/mob_spawn/human/miner(loc)
			new /turf/open/floor/plating/asteroid/basalt(loc)
		if(13)//sailing the ocean blue
			visible_message("<span class='userdanger'>Water pours out of the portal, followed by a strange vessel. It's occupied.</span>")
			playsound(loc,'sound/ambience/shore.ogg', 150, FALSE, 50, TRUE, TRUE)
			new /obj/vehicle/ridden/lavaboat/dragon(loc)
			new /obj/item/oar(loc)
			if(prob(50))
				new /obj/item/clothing/under/costume/sailor(loc)
			if(prob(50))
				new /obj/item/pneumatic_cannon/speargun(loc)
				new /obj/item/storage/magspear_quiver(loc)
				new /obj/item/throwing_star/magspear(loc)
				new /obj/item/throwing_star/magspear(loc)
				new /obj/item/throwing_star/magspear(loc)
				new /obj/item/throwing_star/magspear(loc)
				new /obj/item/throwing_star/magspear(loc)
				new /mob/living/simple_animal/hostile/carp(loc)
			if(prob(45))
				new /obj/item/clothing/suit/space/hardsuit/carp(loc)
				new /mob/living/simple_animal/hostile/carp(loc)
			if(prob(45))
				new /obj/item/gun/magic/hook(loc)
				new /mob/living/simple_animal/hostile/carp(loc)
			if(prob(45))
				new /obj/item/reagent_containers/food/snacks/carpmeat(loc)
				new /obj/item/reagent_containers/food/snacks/carpmeat(loc)
			if(prob(35))
				new /obj/item/guardiancreator/carp(loc)
				new /mob/living/simple_animal/hostile/carp/megacarp(loc)
			if(prob(25))
				new /obj/item/book/granter/martial/carp(loc)
				new /mob/living/simple_animal/hostile/carp/megacarp(loc)
			if(prob(35))
				new /obj/item/grenade/spawnergrenade/spesscarp(loc)
				new /mob/living/simple_animal/hostile/carp/megacarp(loc)
			new /mob/living/simple_animal/hostile/carp/megacarp(loc)
			new /mob/living/simple_animal/hostile/carp(loc)
			new /turf/open/water(loc)
		if(14)//hydroponics forest
			visible_message("<span class='userdanger'>You catch a glimpse of a strange forest. Smells like weed and bad choices.</span>")
			playsound(loc,'sound/ambience/shore.ogg', 150, FALSE, 50, TRUE, TRUE)
			if(prob(45))
				new /obj/item/circuitboard/machine/biogenerator(loc)
				new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			if(prob(35))
				new /obj/item/gun/energy/floragun(loc)
				new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/seed_extractor(loc)
				new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			if(prob(45))
				new /obj/item/circuitboard/machine/plantgenes(loc)
			else
				new /obj/item/circuitboard/machine/hydroponics(loc)
			if(prob(15))
				new /obj/item/circuitboard/machine/hydroponics(loc)
				new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			if(prob(15))
				new /obj/item/circuitboard/machine/hydroponics(loc)
			if(prob(15))
				new /obj/item/seeds/gatfruit(loc)
				new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			if(prob(45))
				new /obj/item/seeds/random(loc)
			if(prob(45))
				new /obj/item/seeds/random(loc)
				new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			if(prob(45))
				new /obj/item/seeds/random(loc)
			if(prob(45))
				new /obj/item/seeds/random(loc)
				new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			if(prob(45))
				new /obj/item/seeds/random(loc)
			if(prob(45))
				new /obj/item/seeds/cannabis(loc)
			new /obj/item/clothing/gloves/botanic_leather(loc)
			new /obj/item/cultivator/rake(loc)
			new /obj/structure/spacevine(loc)
			new /mob/living/simple_animal/hostile/venus_human_trap(loc)
			new /turf/open/floor/grass(loc)

		if(15)//the cultists amoung us
			visible_message("<span class='userdanger'>Chanting and a hateful red glow spill through the portal.</span>")
			playsound(loc,'sound/spookoween/ghost_whisper.ogg', 100, FALSE, 50, TRUE, TRUE)
			if(prob(50))
				new /obj/item/soulstone/anybody(loc)
				new /obj/item/soulstone/anybody(loc)
				new /obj/structure/constructshell(loc)
				new /mob/living/simple_animal/hostile/construct/builder/hostile(loc)
			if(prob(45))
				new /obj/item/borg/upgrade/modkit/lifesteal(loc)
				new /obj/item/bedsheet/cult(loc)
				new /mob/living/simple_animal/hostile/construct/wraith/hostile(loc)
			if(prob(50))
				new /obj/item/stack/sheet/runed_metal/ten(loc)
			if(prob(35))
				new /obj/item/sharpener/cult(loc)
				new /mob/living/simple_animal/hostile/construct/builder/hostile(loc)
			if(prob(15))
				new /obj/item/cult_bastard(loc)
				new /mob/living/simple_animal/hostile/construct/armored/hostile(loc)
			if(prob(35))
				new /obj/item/cult_shift(loc)
				new /mob/living/simple_animal/hostile/construct/builder/hostile(loc)
			if(prob(45))
				new /obj/item/gem/bloodstone(loc)
				new /mob/living/simple_animal/hostile/construct/builder/hostile(loc)
			if(prob(35))
				new /obj/item/clothing/suit/space/hardsuit/cult/(loc)
				new /mob/living/simple_animal/hostile/construct/builder/hostile(loc)
			new /mob/living/simple_animal/hostile/construct/armored/hostile(loc)
			new /mob/living/simple_animal/hostile/construct/wraith/hostile(loc)
			new /obj/structure/destructible/cult/pylon(loc)
			new /turf/open/floor/plasteel/cult(loc)
		if(16)//the backroom freezer
			visible_message("<span class='userdanger'>The faint hallogen glow of a faraway kitchen greets you.</span>")
			if(prob(45))
				new /obj/item/kitchen/knife/bloodletter(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(55))
				new /obj/item/clothing/gloves/butchering(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(45))
				new /obj/item/reagent_containers/food/snacks/store/bread/meat(loc)
				new /obj/item/reagent_containers/food/snacks/store/bread/meat(loc)
				new /obj/item/reagent_containers/food/snacks/store/bread/meat(loc)
			if(prob(35))
				new /obj/item/reagent_containers/food/snacks/pizza/dank(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(25))
				new /obj/item/reagent_containers/food/snacks/meat/steak/gondola(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(35))
				new /obj/item/reagent_containers/food/snacks/burger/roburgerbig(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(35))
				new /obj/item/kitchen/knife/butcher(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(35))
				new /obj/item/flamethrower/full(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(45))
				new /obj/item/sharpener(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(25))
				new /obj/item/sharpener/super(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/gibber(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/chem_master/condi(loc)
				new /mob/living/simple_animal/hostile/killertomato(loc)
			new /mob/living/simple_animal/hostile/alien/maid(loc)
			new /turf/open/floor/plasteel/kitchen_coldroom/freezerfloor(loc)
		if(17)//legion miniboss
			visible_message("<span class='userdanger'>The ground quakes. An immense figure reaches through the portal, crouching to squeeze through.</span>")
			playsound(loc,'sound/magic/knock.ogg', 100, FALSE, 50, TRUE, TRUE)
			new /mob/living/simple_animal/hostile/big_legion(loc)
			if(prob(75))
				new /obj/structure/closet/crate/necropolis/tendril(loc)
			new /turf/open/indestructible/necropolis(loc)
		if(18)//xenobiologist's hubris
			visible_message("<span class='userdanger'>You catch a glimpse of a wobbling sea of slimy friends. An abused-looking keeper slips through the portal.</span>")
			playsound(loc,'sound/effects/footstep/slime1.ogg', 100, FALSE, 50, TRUE, TRUE)
			if(prob(25))
				new /obj/item/slime_extract/adamantine(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(35))
				new /obj/item/slime_extract/gold(loc)
			if(prob(45))
				new /obj/item/extinguisher/advanced(loc)
			if(prob(25))
				new /obj/item/slimepotion/slime/renaming(loc)
				new /mob/living/simple_animal/slime/random(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(25))
				new /obj/item/slimepotion/slime/sentience(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(25))
				new /obj/item/slimepotion/transference(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(45))
				new /obj/item/circuitboard/computer/xenobiology(loc)
				new /obj/item/slime_extract/grey(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(45))
				new /obj/item/circuitboard/machine/processor/slime(loc)
				new /mob/living/simple_animal/slime/random(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(25))
				new /obj/item/armorpolish/adamantine(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(45))
				new /obj/item/slime_cookie/purple(loc)
				new /obj/item/slime_cookie/purple(loc)
				new /obj/item/slime_cookie/purple(loc)
			if(prob(45))
				new /obj/item/storage/box/monkeycubes(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(35))
				new /obj/item/slimepotion/speed(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(45))
				new /obj/item/slimepotion/slime/slimeradio(loc)
				new /mob/living/simple_animal/slime/random(loc)
			if(prob(35))
				new /mob/living/simple_animal/pet/dog/corgi/puppy/slime(loc)
			new /obj/effect/mob_spawn/human/scientist(loc)
			new /turf/open/floor/mineral/titanium/purple(loc)
			new /mob/living/simple_animal/slime/random(loc)
		if(19)//lost abductor
			visible_message("<span class='userdanger'>You glimpse a frigid wreckage. A large block of something slips through the portal.</span>")
			playsound(loc,'sound/effects/break_stone.ogg', 100, FALSE, 50, TRUE, TRUE)
			if(prob(45))
				new /obj/item/stack/sheet/mineral/abductor(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(30))
				new /obj/item/clothing/under/abductor(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(35))
				new /obj/item/weldingtool/abductor(loc)
			if(prob(30))
				new /obj/item/scalpel/alien(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/plantgenes/vault(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(35))
				new /obj/item/organ/heart/gland/heals(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(35))
				new /obj/item/organ/heart/gland/ventcrawling(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(35))
				new /obj/item/organ/heart/gland/slime(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(10))
				new /obj/item/organ/heart/gland/spiderman(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(35))
				new /obj/item/wrench/abductor(loc)
				new /obj/item/screwdriver/abductor(loc)
			if(prob(35))
				new /obj/item/crowbar/abductor(loc)
				new /obj/item/multitool/abductor(loc)
			if(prob(15))
				new /obj/item/abductor_machine_beacon/chem_dispenser(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			if(prob(35))
				new /obj/item/clothing/suit/armor/abductor/vest(loc)
				new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			new /obj/structure/fluff/iced_abductor(loc)
			new /mob/living/simple_animal/hostile/asteroid/polarbear(loc)
			new /turf/open/floor/mineral/abductor(loc)
		if(20)//hey, free elite tumor!
			visible_message("<span class='userdanger'>A large, pulsating structure falls through the portal and crashes to the floor.</span>")
			playsound(loc,'sound/effects/break_stone.ogg', 100, FALSE, 50, TRUE, TRUE)
			new /obj/structure/elite_tumor(loc)
			new /turf/open/floor/plating/asteroid/basalt(loc)
		if(21)//*you flush the toilet.*
			visible_message("<span class='userdanger'>You hear the faint noise of a long flush.</span>")
			new /obj/structure/toilet(loc)
			new /obj/effect/decal/remains(loc)
			new /obj/item/newspaper(loc)
			new /turf/open/floor/plasteel/white(loc)
		if(22)//Research & Zombies
			visible_message("<span class='userdanger'>Flashing lights and quarantine alarms echo through the portal. You smell rotting flesh and plasma.</span>")
			playsound(loc,'sound/misc/bloblarm.ogg', 120, FALSE, 50, TRUE, TRUE)
			if(prob(35))
				new /obj/item/storage/box/rndboards(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(35))
				new /obj/item/storage/box/stockparts/deluxe(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(15))
				new /obj/effect/spawner/lootdrop/stockparts(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(15))
				new /obj/effect/spawner/lootdrop/stockparts(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(15))
				new /obj/effect/spawner/lootdrop/stockparts(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(15))
				new /obj/effect/spawner/lootdrop/stockparts(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(30))
				new /obj/item/circuitboard/machine/rdserver(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(35))
				new /obj/item/research_notes/loot/big(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			else
				new /obj/item/research_notes/loot/medium(loc)
			if(prob(35))
				new /obj/item/research_notes/loot/medium(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			else
				new /obj/item/research_notes/loot/small(loc)
			if(prob(35))
				new /obj/item/pneumatic_cannon(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			if(prob(45))
				new /obj/item/research_notes/loot/medium(loc)
				new /mob/living/simple_animal/hostile/zombie(loc)
			else
				new /obj/item/research_notes/loot/small(loc)
			new/turf/open/floor/mineral/titanium/purple(loc)
			new /mob/living/simple_animal/hostile/zombie(loc)
		if(23)//Silverback's locker room
			visible_message("<span class='userdanger'>You catch a glimpse of verdant green. Smells like a locker room.</span>")
			playsound(loc,'sound/creatures/gorilla.ogg', 75, FALSE, 50, TRUE, TRUE)
			new /mob/living/simple_animal/hostile/gorilla(loc)
			new /mob/living/simple_animal/hostile/gorilla(loc)
			if(prob(35))
				new /obj/item/circuitboard/machine/clonescanner(loc)
			if(prob(35))
				new /obj/item/circuitboard/computer/scan_consolenew(loc)
			if(prob(25))
				new /obj/item/reagent_containers/autoinjector/magillitis(loc)
				new /mob/living/simple_animal/hostile/gorilla(loc)
			if(prob(35))
				new /obj/item/dnainjector/thermal(loc)
				new /mob/living/simple_animal/hostile/gorilla(loc)
			if(prob(35))
				new /obj/item/storage/box/gorillacubes(loc)
				new /mob/living/simple_animal/hostile/gorilla(loc)
			if(prob(35))
				new /obj/item/dnainjector/dwarf(loc)
				new /mob/living/simple_animal/hostile/gorilla(loc)
			if(prob(35))
				new /obj/item/dnainjector/heatmut(loc)
				new /mob/living/simple_animal/hostile/gorilla(loc)
			if(prob(35))
				new /obj/item/dnainjector/gigantism(loc)
			if(prob(35))
				new /obj/item/dnainjector/firebreath(loc)
				new /mob/living/simple_animal/hostile/gorilla(loc)
			if(prob(35))
				new /mob/living/simple_animal/hostile/gorilla(loc)
				new /obj/item/dnainjector/telemut/darkbundle(loc)
			if(prob(35))
				new /obj/item/dnainjector/insulated(loc)
				new /mob/living/simple_animal/hostile/gorilla(loc)
			new /obj/item/sequence_scanner(loc)
			new /obj/structure/flora/grass/jungle(loc)
			new /turf/open/indestructible/grass/jungle(loc)