
// ###### HOS ######
/obj/structure/closet/secure_closet/hos/PopulateContents()
	..()
	new /obj/item/cartridge/hos(src)
	new /obj/item/radio/headset/heads/hos/alt(src)
	new /obj/item/radio/headset/heads/hos(src)
	new /obj/item/storage/lockbox/medal/sec(src)
	new /obj/item/megaphone/sec(src)
	new /obj/item/holosign_creator/security(src)
	new /obj/item/storage/lockbox/loyalty(src)
	new /obj/item/storage/box/flashbangs(src)
	new /obj/item/gun/energy/e_gun/hos(src)
	new /obj/item/flashlight/seclite(src)
	new /obj/item/pinpointer/nuke(src)
	new /obj/item/clothing/gloves/combat(src)
	new /obj/item/storage/belt/security/chief/full(src)
	new /obj/item/clothing/glasses/hud/security/sunglasses/hos(src)	
	new /obj/item/clothing/shoes/xeno_wraps/jackboots(src)
	new /obj/item/circuitboard/machine/techfab/department/armory(src)
	new /obj/item/storage/photo_album/HoS(src)
	new /obj/item/clipboard/yog/paperwork/hos(src)
	new /obj/item/radio/security(src)
	new /obj/item/storage/bag/garment/hos(src)

// ###### WARDEN ######
/obj/structure/closet/secure_closet/warden/PopulateContents()
	..()
	new /obj/item/radio/headset/headset_sec(src)
	new /obj/item/clothing/glasses/hud/security/sunglasses(src)
	new /obj/item/holosign_creator/security(src)
	new /obj/item/storage/box/zipties(src)
	new /obj/item/megaphone/sec(src)
	new /obj/item/storage/box/flashbangs(src)
	new /obj/item/storage/belt/security/full(src)
	new /obj/item/flashlight/seclite(src)
	new /obj/item/clothing/gloves/krav_maga/sec(src)
	new /obj/item/door_remote/head_of_security(src)
	new /obj/item/gun/ballistic/shotgun/automatic/combat/compact(src)
	new /obj/item/clipboard/yog/paperwork/warden(src)
	new /obj/item/radio/security(src)
	new /obj/item/storage/bag/garment/warden(src)

// ###### HOP ######
/obj/structure/closet/secure_closet/hop/PopulateContents()
	..()
	new /obj/item/storage/lockbox/medal/service(src)
	new /obj/item/cartridge/hop(src)
	new /obj/item/radio/headset/heads/hop(src)
	new /obj/item/storage/box/ids(src)
	new /obj/item/storage/box/ids(src)
	new /obj/item/megaphone/command(src)
	new /obj/item/assembly/flash/handheld(src)
	new /obj/item/clothing/glasses/sunglasses(src)
	new /obj/item/clothing/glasses/hud/personnel(src)
	new /obj/item/restraints/handcuffs/cable/zipties(src)
	new /obj/item/clothing/neck/petcollar(src)
	new /obj/item/clothing/suit/armor/vest/alt(src)		
	new /obj/item/pet_carrier(src)
	new /obj/item/door_remote/civillian(src)
	new /obj/item/circuitboard/machine/techfab/department/service(src)
	new /obj/item/storage/photo_album/HoP(src)
	new /obj/item/clipboard/yog/paperwork/hop(src)
	new /obj/item/gun/energy/e_gun/mini(src) //hop doesn't get a proper gun
	new /obj/item/storage/bag/garment/hop(src)

// ###### CAPTAIN ######

/obj/structure/closet/secure_closet/captains/PopulateContents()
	..()
	new /obj/item/clothing/neck/petcollar(src)
	new /obj/item/pet_carrier(src)
	new /obj/item/cartridge/captain(src)
	new /obj/item/storage/box/silver_ids(src)
	new /obj/item/radio/headset/heads/captain/alt(src)
	new /obj/item/radio/headset/heads/captain(src)
	new /obj/item/restraints/handcuffs/cable/zipties(src)
	new /obj/item/storage/belt/sabre(src)
	new /obj/item/door_remote/captain(src)
	new /obj/item/storage/photo_album/Captain(src)
	new /obj/item/clipboard/yog/paperwork/captain(src)
	new /obj/item/radio/security(src)
	new /obj/item/storage/bag/garment/captain(src)

// ###### RD ######

/obj/structure/closet/secure_closet/RD/PopulateContents()
	..()
	new /obj/item/cartridge/rd(src)
	new /obj/item/radio/headset/heads/rd(src)
	new /obj/item/tank/internals/air(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/megaphone/command(src)
	new /obj/item/storage/lockbox/medal/sci(src)
	new /obj/item/clothing/suit/armor/reactive/teleport(src)
	new /obj/item/assembly/flash/handheld(src)
	new /obj/item/laser_pointer(src)
	new /obj/item/door_remote/research_director(src)
	new /obj/item/circuitboard/machine/techfab/department/science(src)
	new /obj/item/storage/photo_album/RD(src)
	new /obj/item/clipboard/yog/paperwork/rd(src)
	new /obj/item/storage/bag/garment/research_director(src)
	new /obj/item/analyzer/ranged(src)
