/obj/item/twohanded/fishingrod/tech
	name = "advanced fishing rod"
	desc = "An embedded universal constructor along with micro-fusion generator makes this marvel of technology never run out of bait. Interstellar treaties prevent using it outside of recreational fishing. And you can fish with this. "
	icon_state = "fishing_rod_science"
	item_state = "fishing_rod"
	lefthand_file = 'yogstation/icons/mob/inhands/equipment/fishing_lefthand.dmi'
	righthand_file = 'yogstation/icons/mob/inhands/equipment/fishing_righthand.dmi'
	icon = 'dripstation/icons/obj/fishing.dmi'

/obj/item/twohanded/fishingrod/tech/Initialize(mapload)
	. = ..()
	var/obj/item/reagent_containers/food/snacks/bait/synthetic/infinite_supply_of_bait = new(src)
	bait = infinite_supply_of_bait
	recalculate_power()

/obj/item/twohanded/fishingrod/tech/consume_bait()
	return

/obj/item/twohanded/fishingrod/tech/attackby(obj/item/B, mob/user, params)
	return

/obj/item/twohanded/fishingrod/tech/AltClick(mob/living/user)
	if(!bait)
		var/obj/item/reagent_containers/food/snacks/bait/synthetic/infinite_supply_of_bait = new(src)
		bait = infinite_supply_of_bait
		recalculate_power()
	return

/// These are generated by tech fishing rod
/obj/item/reagent_containers/food/snacks/bait/synthetic
	name = "synthetic doughball"
	icon = 'dripstation/icons/obj/fishing.dmi'
	icon_state = "doughball"
	//preserved_food = TRUE
	list_reagents = list(/datum/reagent/consumable/nutriment/protein = 1)
	tastes = list("dough" = 1)
	foodtype = GRAIN
	w_class = WEIGHT_CLASS_TINY
	fishing_power = 20